export const destinations = [
  {
    id: 1,
    name: "Santorini",
    country: "Greece",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    description: "Experience breathtaking sunsets and whitewashed houses overlooking the blue sea.",
    price: 850,
    rating: 5,
  },
  {
    id: 2,
    name: "Kyoto",
    country: "Japan",
    image: "https://lp-cms-production.imgix.net/2023-02/shutterstock_1017748444.jpg?auto=format,compress&q=72&w=1095&fit=crop&crop=faces,edges",
    description: "Discover ancient temples, cherry blossoms, and traditional Japanese culture.",
    price: 920,
    rating: 5,
  },
  {
    id: 3,
    name: "Bali",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    description: "Relax on tropical beaches, explore lush jungles, and enjoy serene temples.",
    price: 780,
    rating: 4,
  },
  {
    id: 4,
    name: "Paris",
    country: "France",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    description: "Fall in love with the City of Lights — from the Eiffel Tower to cozy cafés.",
    price: 950,
    rating: 5,
  },
  {
    id: 5,
    name: "Cappadocia",
    country: "Turkey",
    image: "https://cdn.getyourguide.com/image/format=auto,fit=crop,gravity=auto,quality=60,width=450,height=450,dpr=2/tour_img/6309da2ade21f.jpeg",
    description: "Float above fairy chimneys in a hot air balloon and explore ancient caves.",
    price: 720,
    rating: 4,
  },
  {
    id: 6,
    name: "Maldives",
    country: "Maldives",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    description: "Stay in luxury water villas and enjoy crystal-clear turquoise waters.",
    price: 1200,
    rating: 5,
  },
  {
    id: 7,
    name: "Swiss Alps",
    country: "Switzerland",
    image: "https://ariajourneys.com/wp-content/uploads/2017/02/ski-chalet-Zermatt.jpg",
    description: "Ski on the majestic Alps and enjoy scenic mountain villages.",
    price: 1100,
    rating: 5,
  },
  {
    id: 8,
    name: "Dubai",
    country: "UAE",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=800&q=80",
    description: "Luxury shopping, desert safaris, and the tallest skyscraper in the world.",
    price: 880,
    rating: 4,
  },
  {
    id: 9,
    name: "Rome",
    country: "Italy",
    image: "https://i.natgeofe.com/k/a6c9f195-de20-445d-9d36-745ef56042c5/OG_Colosseum_Ancient-Rome_KIDS_1122_3x2.jpg",
    description: "Walk through history in the Eternal City — Colosseum, Vatican, and more.",
    price: 890,
    rating: 5,
  },
  {
    id: 10,
    name: "Phuket",
    country: "Thailand",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    description: "Beautiful beaches, vibrant nightlife, and delicious Thai cuisine.",
    price: 720,
    rating: 4,
  },
  {
    id: 11,
    name: "Machu Picchu",
    country: "Peru",
    image: "https://images.unsplash.com/photo-1526406915894-7bcd65f60845?auto=format&fit=crop&w=800&q=80",
    description: "Explore the ancient Incan citadel set high in the Andes Mountains.",
    price: 950,
    rating: 5,
  },
  {
    id: 12,
    name: "New York City",
    country: "USA",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    description: "The city that never sleeps — skyscrapers, Broadway, and endless energy.",
    price: 1000,
    rating: 5,
  },
];
